### ISSUE TITLE
Support for stages with multiple jobs

### ISSUE THREAD

**Issue by borgesp** [heikkipora/gitlab-radiator#13]
Hi, great initiative, very useful !
Do you have plans to support stages with multiple jobs ?
I have 1 stage with 2 jobs but only one of them appears in graph.
Thanks, Pedro Borges

**Comment by heikkipora** [comment]
Thanks! That's something that clearly needs to be addressed in the future.

I'm thinking of rendering the build pipeline stages and jobs as an SVG graph (instead of the rather simple HTML it is now). That would be at easier to scale and fit into the build boxes. The current implementation also limits the visible build stages to four at once and would be improved at the same time.

**Comment by borgesp** [comment]
Great to hear, looking forward to it :-)

All the best, Pedro Borges

**Comment by leflamm** [comment]
Would love to have that, too. Thx for your work!

**Comment by heikkipora** [comment]
A new major release is just out that includes the feature you suggested. See https://github.com/heikkipora/gitlab-radiator/releases/tag/2.0.3
Available on www.npmjs.com already.
