### ISSUE TITLE
Show all CI jobs for a project that are running

### ISSUE THREAD

**Issue by sfozz** [heikkipora/gitlab-radiator#71]
If we have a project where there could be multiple instances of the CI pipeline running it would be useful to be able to view them independently. For example there is a test, build and deploy pipeline that runs against the main branch, but when engineers commit to branches we only run the test pipeline.

Is there a possibility of splitting the pipelines based on the branch, tag or MR?

**Comment by danrhjones** [comment]
Sorry to bump an old issue, but did this get addressed?

**Comment by heikkipora** [comment]
It did not. Do you have any ideas of how that might look like - and how it might fit into the current visualisation features ?

**Comment by heikkipora** [comment]
gitlab-radiator tries to visualise things very compactly so that its views fit nicely on a few screens mounted on a wall. A product / project team might have many tens of gitlab-projects in which case it is important to have a single project occupy predictable and compact screen area (preferrably staying put in a fixed location so that its easy for a human to locate it by remembering where it was the last time). In that environment it is not very feasible to show multiple parallel things per project.

However, having an environment where there are one or a couple of projects it might be desirable to show all concurrently running pipelines at the same time - but that is exactly what the GitLab CI pipeline UI does already itself.

**Comment by heikkipora** [comment]
Stale, closing
