### ISSUE TITLE
Show multiple scheduled jobs from project based on a variable

### ISSUE THREAD

**Issue by kivipe** [heikkipora/gitlab-radiator#94]
We are using scheduled pipelines to deploy software in several environments. A variable in the schedule controls the target environment. Gitlab radiator shows only one per project, so if a job fails to environment A, it is overwritten by a successful deployment to B. Would it be possible to show multiple schedules for a project based on a variable?

**Comment by heikkipora** [comment]
That's indeed the case. I'd really like to keep gitlab-radiator's view so that it has a single "project/pipeline ui element" per gitlab-project (related feature request: https://github.com/heikkipora/gitlab-radiator/issues/71).

In your case, would it be sufficient to just show the failed pipeline instead of the latest one in case there are multiple pipelines (for the last commit) with different variable values ? That would at least signal that there's something to investigate (which, for me, is the reason for the whole gitlab-radiator project to exist :-D )

**Comment by heikkipora** [comment]
Stale, closing
